services:
  - type: web
    name: laravel
    env: php
    rootDirectory: .
    buildCommand: composer install && php artisan key:generate && php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
